[WARNING] Try to add scss instead of css
After npm run dev I get error

"ERROR in ./src/modules/index.js 1:0-34 Module not found:
Error: Can't resolve ' sass-loader' in 'E:\Projekty\Webpack_template'
resolve ' sass-loader' in 'E:\Projekty\Webpack_template' Parsed request
is a module using description file:
E:\Projekty\Webpack_template\package.json (relative path: .) resolve as
module looking for modules in E:\Projekty\Webpack_template\node_modules
no extension
ve path: ./node_m E:\Projekty\Webpack_template\node_modules\ sass-loader
doesn't exist                  odules/ sass-loader)st .js
E:\Projekty\Webpack_template\node_modules\ sass-loader.js doesn't exi
exist
st E:\Projekty\Webpack_template\node_modules\ sass-loader doesn't exist
E:\Projekty\node_modules doesn't exist or is not a directory
E:\node_modules doesn't exist or is not a directory webpack 5.24.3
compiled with 1 error in 42 ms".

I tried to resovle it with google but I
didn't find anything helpful. I will add mock content without scss, and
I will try to resolve these problem on the other branch. I decided to
resolve it later cuz it is not critical error